version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vamsasetu
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/yourpassword
      NEO4J_dbms_security_auth__minimum__password__length: 6
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474" # HTTP browser
      - "7687:7687" # bolt
    volumes:
      - neo4jdata:/data
volumes:
  pgdata:
  neo4jdata:
