spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/vamsasetu
    username: youruser
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  data:
    neo4j:
      uri: ${NEO4J_URI:bolt://localhost:7687}
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASSWORD:neo4j}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8080}
jwt:
  secret: ${JWT_SECRET:changeme}
  expireDays: ${JWT_EXPIRE_DAYS:7}
mail:
  host: ${SMTP_HOST:smtp.example.com}
  port: ${SMTP_PORT:587}
  username: ${SMTP_USER:}
  password: ${SMTP_PASS:}
twilio:
  accountSid: ${TWILIO_ACCOUNT_SID:}
  authToken: ${TWILIO_AUTH_TOKEN:}
  phoneNumber: ${TWILIO_PHONE_NUMBER:}
sendgrid:
  apiKey: ${SENDGRID_API_KEY:}
